---
title: "Data Cleaning"
author: "Matilde Jacobsen"
date: "10/12/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

#Importing packages

```{r}
#Set working directory
setwd("/Users/matilde/Desktop/AU/Bachelor project/Color_matching/data_cleaning")
#Load packages
pacman::p_load(tidyverse, jsonlite, rjson, data.table)
#Downloead citations
RStudio.Version()
#Clean environment
rm(list = ls())

```

#Load data
Make a loop for loading the logfiles
```{r}
#specifying data path
dataPath <- 'logfiles/28-10-2020/'
#creating a list of files
list_files <- list.files(path = dataPath,
                         recursive = T,
                         pattern = "json$",
                         full.names = T)
# wmpty data fame with the correct column names
allData <- data.frame(matrix(ncol = 24, nrow = 0))
x <- c("test_part", "rt", "Condition", "Condition_label", "Subject", "Chain", "Generation", "Language", "Hue_source", "Saturation_source", "Lightness_source", "Hue_matched", "Saturation_matched", "Lighness_matched", "Color_label_source", "Color_label_matched", "Language", "basic_colors", "creative_name", "Hue_color_to_name", "Saturation_color_to_name", "Lightness_color_to_name", "Color_label_naming", "responses") 
colnames(allData) <- x


for (i in 1:length(list_files)){

  filePath <- list_files[i]
  
  d <- jsonlite::fromJSON(filePath, flatten=T)
  
  d <- d %>% 
  rename(Chain = info.chain,
         Subject = info.subject,
         Generation = info.generation,
         Language = info.language,
         Condition = info.condition,
         Hue_source = source_color.h,
         Saturation_source = source_color.s,
         Lightness_source = source_color.l,
         Hue_matched = color.h,
         Saturation_matched = color.s,
         Lighness_matched = color.l,
         Color_label_matched = color.color_label,
         Color_label_source = source_color.color_label,
         Hue_color_to_name = color_to_name.h,
         Saturation_color_to_name = color_to_name.s,
         Lightness_color_to_name = color_to_name.l,
         Color_label_naming = color_to_name.color_label) %>% 
  mutate(Condition_label=
    case_when(
      Condition ==2~"Naming transmission" ,
      Condition ==1~"Pure transmission")) %>% 
    select(test_part, rt, Condition, Condition_label, Subject, Chain, Generation, Language, Hue_source, Saturation_source, Lightness_source, Hue_matched, Saturation_matched, Lighness_matched, Color_label_source, Color_label_matched, Language, basic_colors, creative_name, Hue_color_to_name, Saturation_color_to_name, Lightness_color_to_name, Color_label_naming, responses) 
  
  if (nrow(allData) == 0){
    allData <- d
  } else{
    allData <- rbind(allData, d)
  }
  
}
```

#Exstarcting demographics
```{r}
#filtering demographics
demo <- allData %>% 
  filter(test_part == 'demographics') %>% 
  select(Subject, responses)

#Preparing loop
demoData <- data.frame(matrix(ncol = 6, nrow = length(demo$Subject)))
names <- c("Subject","Vision_impairments", "Age", "Gender", "Language_spoken", "Participated_before")
colnames(demoData) <- names
demoData <- left_join(demo, demoData)

#making a loop that extracts all the information from the demographics responses
for (i in 1:length(demo$Subject)){
  matrix <- str_split_fixed(demo[i,2], "\\,",5)
  matrix2 <- str_split_fixed(matrix, "\\:",2)
  demo_df <- as.data.frame(matrix2)
  data_wide <- spread(demo_df, V1, V2)
  
  demoData[i,3] <- as.character(data_wide[1,5])
  demoData[i,4] <- as.character(data_wide[1,1])
  demoData[i,5] <- as.character(data_wide[1,2])
  demoData[i,6] <- as.character(data_wide[1,3])
  demoData[i,7] <- as.character(data_wide[1,4])

  
}  

#Removing punctuations
demoData$Vision_impairments <- gsub('[[:punct:] ]+','',demoData$Vision_impairments)
demoData$Age <- gsub('[[:punct:] ]+','',demoData$Age)
demoData$Gender <- gsub('[[:punct:] ]+','',demoData$Gender)
demoData$Language_spoken <- gsub('[[:punct:] ]+','',demoData$Language_spoken)
demoData$Participated_before <- gsub('[[:punct:] ]+','',demoData$Participated_before)

#Removing responses column
demoData <- demoData %>% select(-responses)

#merge demographics with allData
allData <- merge(allData, demoData)

#fixing some rows
fix <- allData %>% filter(Age == "no")
fix$Age <- fix$Gender
fix$Gender <- fix$Language_spoken
fix$Language_spoken <- fix$Participated_before
fix$Participated_before <- "no"
#and replacing them 
allData <- subset(allData, Age!="no")
allData <- rbind(allDataT, fix)

```

#Extractin confidence ratings
```{r}
allData <- allData %>% 
  mutate(Color_label_matched = case_when(
          Color_label_matched == "seed sennepsgul" ~ "seed mustard",
          Color_label_matched == "seed græsgrøn" ~ "seed grass green",
          Color_label_matched == "seed havblå" ~ "seed ocean blue",
          Color_label_matched == "seed mørk rosa" ~ "seed dark rose",
          TRUE ~ Color_label_matched)) %>%
  mutate(lagged_label = lag(Color_label_matched, n = 1))
#filtering confidence ratings
confidence <- allData %>% 
  filter(test_part == 'confidence') %>% 
  select(Subject, responses, lagged_label) %>%
  na.omit() %>% 
  rename(Color_label_matched = lagged_label,
         Confidence = responses)

confidence$Confidence <- str_replace_all(confidence$Confidence, "..\\bconfidence..", "")
confidence$Confidence <- str_replace_all(confidence$Confidence, "\\}", "")
confidence$Confidence <- as.numeric(confidence$Confidence)


```

#Making color matching df
Filter rows containing color matching and selecting which rows to keep
+ Creating the column with focal hue values
```{r}
color_matching <- allData %>% 
  filter(test_part == 'matching') %>% 
  select(Subject, Language, Age, Gender, Language_spoken, rt, Condition, Condition_label,  Chain, Generation, Language, Color_label_source, Color_label_matched, Lightness_source, Lighness_matched, Saturation_source, Saturation_matched, Hue_source, Hue_matched) 


#Add 360 when matched hue is between 0 and 20 
color_matching$Hue_matched <- as.numeric(color_matching$Hue_matched)
color_matching$Hue_matched <- case_when(color_matching$Hue_matched < 30 ~ color_matching$Hue_matched + 360,
                               color_matching$Hue_matched > 30 ~ color_matching$Hue_matched)
color_matching$Hue_source <- case_when(color_matching$Hue_source < 30 ~ color_matching$Hue_source + 360,
                               color_matching$Hue_source > 30 ~ color_matching$Hue_source)
#Subtract 360 when matched hue is above 360 
color_matching$Hue_matched <- case_when(color_matching$Hue_matched > 360 ~ color_matching$Hue_matched - 360,
                               color_matching$Hue_matched < 360 ~ color_matching$Hue_matched)
color_matching$Hue_source <- case_when(color_matching$Hue_source > 360 ~ color_matching$Hue_source - 360,
                               color_matching$Hue_source < 360 ~ color_matching$Hue_source)

#Hues of each focal color 
red <- 12.2 + 360
yellow <- 62.4
green <- 136.5
blue <- 193.6
#Hues of each seed color 
red_blue <- 327.55
yellow_red <- 49.85
green_yellow <- 117.98
blue_green <- 179.34
#Rename color labels to English and add focal wavelengths
color_matching <- color_matching %>% 
  mutate(Color_label_matched = case_when(
          Color_label_matched == "seed sennepsgul" ~ "seed mustard",
          Color_label_matched == "seed græsgrøn" ~ "seed grass green",
          Color_label_matched == "seed havblå" ~ "seed ocean blue",
          Color_label_matched == "seed mørk rosa" ~ "seed dark rose",
          Color_label_matched == "seed mintgrøn" ~ "seed mint green",
          TRUE ~ Color_label_matched)) %>% 
  mutate(Focal = case_when(
          Color_label_matched == "seed mustard" ~ yellow,
          Color_label_matched == "seed grass green" ~ green,
          Color_label_matched == "seed ocean blue" ~ blue,
          Color_label_matched == "seed dark rose" ~ red)) %>% 
  mutate(Seed = case_when(
          Color_label_matched == "seed mustard" ~ yellow_red,
          Color_label_matched == "seed grass green" ~ green_yellow,
          Color_label_matched == "seed ocean blue" ~ blue_green,
          Color_label_matched == "seed dark rose" ~ red_blue))

#removing test match
color_matching <- subset(color_matching, Color_label_matched!="seed mint green")

#As numeric
color_matching$Seed <- as.numeric(color_matching$Seed)

#Add column with difference between matched hue and focal:
color_matching <- color_matching %>% 
  mutate(
    Dif = Focal - Hue_matched,
    Rel_dif = 100/(Focal - Seed)*Dif,
    Accuracy = Hue_source - Hue_matched
  )

#As factors cleaned
color_matching$Condition <- as.factor(color_matching$Condition)
color_matching$Chain <- as.factor(color_matching$Chain)
color_matching$Color_label_matched <- as.factor(color_matching$Color_label_matched)
color_matching$Gender <- as.factor(color_matching$Gender)
color_matching$Language <- as.factor(color_matching$Language)

#unique danish
color_matching_danish <- color_matching %>% filter(Language == "Danish")
us <- unique(color_matching$Subject)
usd <- unique(color_matching_danish$Subject)

#Adding confidence ratings
color_matching <- left_join(confidence, color_matching)

#Writing the CSV file to directory with date of writing automatically generated
write.csv(color_matching, file=paste("color_matching",Sys.Date(), sep = "", ".csv"))


```


#Making color naming df

```{r}
color_naming_df <- allData %>% 
  filter(test_part == 'naming') %>% 
  select(Condition_label, basic_colors, creative_name, Chain, Generation, Subject, Condition, Language, Hue_color_to_name, Saturation_color_to_name, Lightness_color_to_name, Color_label_naming, Vision_impairments, Age, Gender, Language_spoken, Participated_before) 

us <- unique(color_naming_df$Subject)

write.csv(color_naming_df, file=paste("color_naming",Sys.Date(),sep = "", ".csv"))

```

#Making reflective responses df
```{r}

#Reflecting
d_reflect <- allData %>% 
  filter(test_part == 'post-experiment') %>% 
  select(responses, Subject, Language_spoken, Gender, Age)

#Cleaning columns
d_reflect$responses <- str_replace_all(d_reflect$responses, "..\\blanguage..", "") 
d_reflect$responses <- str_replace_all(d_reflect$responses, "\\}", "") 
d_reflect$responses <- str_replace_all(d_reflect$responses, "\\p{quotation mark}", "")

##Remove empty rows
d_reflect$responses <- as.character(d_reflect$responses)
d_reflect$responses[d_reflect$responses==""] <- NA
d_reflect$responses <- as.factor(d_reflect$responses)
d_reflect <- na.omit(d_reflect)


write.csv(d_reflect, file=paste("reflect",Sys.Date(),sep = "", ".csv"))
```

